import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderTop from "./components/Headder/HeaderTop";
import HeaderMain from "./components/Headder/HeaderMain";
import NavbarMain from "./components/Navbar/NavbarMain";
import Footer from "./components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <>
    <html lang="en">
      
      <body
        className={ `bg-white dark:bg-gray-950  ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HeaderTop />
        <HeaderMain /> 
        <NavbarMain /> 
        {children}
        <Footer /> 
      </body>
    </html>
   </>
  );
}
